### ISSUE TITLE
CMAKE_CXX_FLAGS for choreonoid

### ISSUE THREAD

**Issue by fkanehiro** [jenkinshrg/drcutil#27]
@mehdi-benallegue
CMAKE_CXX_FLAGS defined in cmake_install_with_option() is ignored when install_choreonoid() is called.
Because CMAKE_CXX_FLAGS is also defined in install_choreonoid() and given to cmake twice.
Can you can this so that CMAKE_CXX_FLAGS is defined only in cmake_install_with_option()?

https://github.com/jenkinshrg/drcutil/blob/jenkins/install.sh#L185

**Comment by mehdi-benallegue** [comment]
Should be fixed with pull request https://github.com/jenkinshrg/drcutil/pull/28
