### ISSUE TITLE
No expression of "OPENHRP_3_1" of choreonoid when run "./update.sh"

### ISSUE THREAD

**Issue by YiliQin** [jenkinshrg/drcutil#65]
I am trying to run the script "./update.sh" but encountered the following errors (choreonoid.log):

[  1%] Built target pugixml
[  2%] Built target cnoid-nameserver
[  2%] Built target CnoidCorba
[  3%] Built target CnoidOpenRTM
[  3%] Built target symlink_to_model
[  4%] Built target CnoidPyUtil
[ 14%] Built target CnoidUtil
[ 14%] Built target PyQtCore
[ 14%] Built target PyQtGui
[ 14%] Built target PyCorba
[ 14%] Built target doc
[ 15%] Building CXX object ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/OpenHRPControllerBase.cpp.o
<command-line>:0:1: error: macro names must be identifiers
[ 20%] Built target CnoidAISTCollisionDetector
[ 20%] Built target CnoidAssimpSceneLoader
[ 20%] Building CXX object ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/corba/OpenHRP/3.1/OpenHRPCommonSk.cpp.o
<command-line>:0:1: error: macro names must be identifiers
/home/yili/src/choreonoid/ext/openhrp-plugin/OpenHRPControllerBase.cpp:137:18: error: #elif with no expression
 #elif OPENHRP_3_1
                  ^
ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/build.make:345: recipe for target 'ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/corba/OpenHRP/3.1/OpenHRPCommonSk.cpp.o' failed
make[2]: *** [ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/corba/OpenHRP/3.1/OpenHRPCommonSk.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 30%] Built target CnoidBody
ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/build.make:332: recipe for target 'ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/OpenHRPControllerBase.cpp.o' failed
make[2]: *** [ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/OpenHRPControllerBase.cpp.o] Error 1
CMakeFiles/Makefile2:4900: recipe for target 'ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/all' failed
make[1]: *** [ext/openhrp-plugin/CMakeFiles/CnoidOpenHRP3.1.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 55%] Built target CnoidBase
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YiliQin** [comment]
We checked out the  openhrp-plugin to the old commit [93ad2014f89bab5fce8e55568196c153bd634305](https://github.com/isri-aist/openhrp-plugin/commit/93ad2014f89bab5fce8e55568196c153bd634305) and the  building passed.

**Comment by mmurooka** [comment]
Close this issue as https://github.com/isri-aist/openhrp-plugin/pull/3 should fix it. (But I didn't have the permissions to close it.)
