### ISSUE TITLE
teeでログを残しながらエラーで止まる

### ISSUE THREAD

**Issue by fkanehiro** [jenkinshrg/drcutil#7]
@jun0 さん、
https://github.com/jenkinshrg/drcutil/blob/jenkins/install.sh#L41-L43
でteeを使ってcmakeやmakeのログを残すようにしていますが、こうするとcmakeやmakeがエラーを起こしてもtrapに引っかからずに処理が継続してしまうようです。
両立させる方法はないでしょうか。

**Comment by jun0** [comment]
そんな副作用が…
https://github.com/jenkinshrg/drcutil/pull/8
で修正しました。set -o pipefail によって foo | bar で foo が非0を返すと全体が非0を返すようになりました。僕の経験ではまず問題になることはない変化ですが、一応頭に入れておいて下さい。
